# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=gmake
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef "CFG"
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=$(OUTDIR)/RTSEngine
CFG_INC=-I/usr/local/include 
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/AttackBehavior.o $(OUTDIR)/BasicConfiguration.o \
	$(OUTDIR)/BasicObject.o $(OUTDIR)/BasicObjectBehaviorManager.o \
	$(OUTDIR)/BasicObjectCommunicationManager.o \
	$(OUTDIR)/BasicObjectDecisionManager.o \
	$(OUTDIR)/BasicObjectParamsManager.o \
	$(OUTDIR)/BasicObjectWorldInfoFrame.o \
	$(OUTDIR)/BasicObjectWorldInfoManager.o $(OUTDIR)/Behavior.o \
	$(OUTDIR)/ConfigurationReader.o $(OUTDIR)/ConfigurationWriter.o \
	$(OUTDIR)/DrawableObject.o $(OUTDIR)/EscapeBehavior.o \
	$(OUTDIR)/extern.o $(OUTDIR)/Flock.o $(OUTDIR)/Formation.o \
	$(OUTDIR)/Gadget.o $(OUTDIR)/GameView.o $(OUTDIR)/GridArea.o \
	$(OUTDIR)/GridElement.o $(OUTDIR)/Group.o \
	$(OUTDIR)/HexagonalMapGrid.o $(OUTDIR)/Layer.o $(OUTDIR)/LineMove.o \
	$(OUTDIR)/MapGrid.o $(OUTDIR)/MapTest.o $(OUTDIR)/MovementManager.o \
	$(OUTDIR)/PatrolBehavior.o $(OUTDIR)/Position.o \
	$(OUTDIR)/RTSEngine.o $(OUTDIR)/TacticalGroup.o \
	$(OUTDIR)/TacticalGroupsManager.o $(OUTDIR)/TextureObject.o \
	$(OUTDIR)/TexturePattern.o $(OUTDIR)/TimeFrameScheduledObject.o \
	$(OUTDIR)/TraceBehavior.o $(OUTDIR)/UI.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/AttackBehavior.o $(OUTDIR)/BasicConfiguration.o \
	$(OUTDIR)/BasicObject.o $(OUTDIR)/BasicObjectBehaviorManager.o \
	$(OUTDIR)/BasicObjectCommunicationManager.o \
	$(OUTDIR)/BasicObjectDecisionManager.o \
	$(OUTDIR)/BasicObjectParamsManager.o \
	$(OUTDIR)/BasicObjectWorldInfoFrame.o \
	$(OUTDIR)/BasicObjectWorldInfoManager.o $(OUTDIR)/Behavior.o \
	$(OUTDIR)/ConfigurationReader.o $(OUTDIR)/ConfigurationWriter.o \
	$(OUTDIR)/DrawableObject.o $(OUTDIR)/EscapeBehavior.o \
	$(OUTDIR)/extern.o $(OUTDIR)/Flock.o $(OUTDIR)/Formation.o \
	$(OUTDIR)/Gadget.o $(OUTDIR)/GameView.o $(OUTDIR)/GridArea.o \
	$(OUTDIR)/GridElement.o $(OUTDIR)/Group.o \
	$(OUTDIR)/HexagonalMapGrid.o $(OUTDIR)/Layer.o $(OUTDIR)/LineMove.o \
	$(OUTDIR)/MapGrid.o $(OUTDIR)/MapTest.o $(OUTDIR)/MovementManager.o \
	$(OUTDIR)/PatrolBehavior.o $(OUTDIR)/Position.o \
	$(OUTDIR)/RTSEngine.o $(OUTDIR)/TacticalGroup.o \
	$(OUTDIR)/TacticalGroupsManager.o $(OUTDIR)/TextureObject.o \
	$(OUTDIR)/TexturePattern.o $(OUTDIR)/TimeFrameScheduledObject.o \
	$(OUTDIR)/TraceBehavior.o $(OUTDIR)/UI.o 

COMPILE=g++ -c   -g -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -g -o "$(OUTFILE)" $(ALL_OBJ) -lalleg-4.0.3 -lalleg_unsharable

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=$(OUTDIR)/RTSEngine
CFG_INC=-I/usr/local/include 
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/AttackBehavior.o $(OUTDIR)/BasicConfiguration.o \
	$(OUTDIR)/BasicObject.o $(OUTDIR)/BasicObjectBehaviorManager.o \
	$(OUTDIR)/BasicObjectCommunicationManager.o \
	$(OUTDIR)/BasicObjectDecisionManager.o \
	$(OUTDIR)/BasicObjectParamsManager.o \
	$(OUTDIR)/BasicObjectWorldInfoFrame.o \
	$(OUTDIR)/BasicObjectWorldInfoManager.o $(OUTDIR)/Behavior.o \
	$(OUTDIR)/ConfigurationReader.o $(OUTDIR)/ConfigurationWriter.o \
	$(OUTDIR)/DrawableObject.o $(OUTDIR)/EscapeBehavior.o \
	$(OUTDIR)/extern.o $(OUTDIR)/Flock.o $(OUTDIR)/Formation.o \
	$(OUTDIR)/Gadget.o $(OUTDIR)/GameView.o $(OUTDIR)/GridArea.o \
	$(OUTDIR)/GridElement.o $(OUTDIR)/Group.o \
	$(OUTDIR)/HexagonalMapGrid.o $(OUTDIR)/Layer.o $(OUTDIR)/LineMove.o \
	$(OUTDIR)/MapGrid.o $(OUTDIR)/MapTest.o $(OUTDIR)/MovementManager.o \
	$(OUTDIR)/PatrolBehavior.o $(OUTDIR)/Position.o \
	$(OUTDIR)/RTSEngine.o $(OUTDIR)/TacticalGroup.o \
	$(OUTDIR)/TacticalGroupsManager.o $(OUTDIR)/TextureObject.o \
	$(OUTDIR)/TexturePattern.o $(OUTDIR)/TimeFrameScheduledObject.o \
	$(OUTDIR)/TraceBehavior.o $(OUTDIR)/UI.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/AttackBehavior.o $(OUTDIR)/BasicConfiguration.o \
	$(OUTDIR)/BasicObject.o $(OUTDIR)/BasicObjectBehaviorManager.o \
	$(OUTDIR)/BasicObjectCommunicationManager.o \
	$(OUTDIR)/BasicObjectDecisionManager.o \
	$(OUTDIR)/BasicObjectParamsManager.o \
	$(OUTDIR)/BasicObjectWorldInfoFrame.o \
	$(OUTDIR)/BasicObjectWorldInfoManager.o $(OUTDIR)/Behavior.o \
	$(OUTDIR)/ConfigurationReader.o $(OUTDIR)/ConfigurationWriter.o \
	$(OUTDIR)/DrawableObject.o $(OUTDIR)/EscapeBehavior.o \
	$(OUTDIR)/extern.o $(OUTDIR)/Flock.o $(OUTDIR)/Formation.o \
	$(OUTDIR)/Gadget.o $(OUTDIR)/GameView.o $(OUTDIR)/GridArea.o \
	$(OUTDIR)/GridElement.o $(OUTDIR)/Group.o \
	$(OUTDIR)/HexagonalMapGrid.o $(OUTDIR)/Layer.o $(OUTDIR)/LineMove.o \
	$(OUTDIR)/MapGrid.o $(OUTDIR)/MapTest.o $(OUTDIR)/MovementManager.o \
	$(OUTDIR)/PatrolBehavior.o $(OUTDIR)/Position.o \
	$(OUTDIR)/RTSEngine.o $(OUTDIR)/TacticalGroup.o \
	$(OUTDIR)/TacticalGroupsManager.o $(OUTDIR)/TextureObject.o \
	$(OUTDIR)/TexturePattern.o $(OUTDIR)/TimeFrameScheduledObject.o \
	$(OUTDIR)/TraceBehavior.o $(OUTDIR)/UI.o 

COMPILE=g++ -c   -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -o "$(OUTFILE)" $(ALL_OBJ) -lalleg-4.0.3 -lalleg_unsharable

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif
